name: Build
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
    - release/**
permissions:
  contents: write
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
      versionCode: ${{ steps.run_number.outputs.versionCode }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - name: Display SemVer
      run: 'echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"'
  build:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
      run: ./gradlew build
    - name: Rename AAR
      run: mv ./build/libs/*.jar ./contrast-accessibility.jar
    - uses: actions/upload-artifact@v4
      with:
        name: contrast-accessibility-jar
        path: ./contrast-accessibility.jar
  release:
    permissions:
      contents: write
    needs:
    - version
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create tag for release
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ needs.version.outputs.version }}
    - id: create_release
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ needs.version.outputs.version }}
        name: Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
  publish-release:
    needs:
    - version
    - release
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: contrast-accessibility-jar
        path: ./
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./contrast-accessibility.jar
        asset_name: contrast-accessibility-v${{ needs.version.outputs.version }}.jar
        asset_content_type: application/zip
  publish-sonatype:
    permissions:
      contents: read
    needs:
    - version
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
      run: |-
        ./gradlew -Pversion=${{ needs.version.outputs.version }} 
        -Ppom.url="https://github.com/${{ github.repository }}" 
        -Ppom.scm.connection="scm:git:git://github.com/${{ github.repository }}" 
        -Ppom.scm.developerConnection="scm:git:ssh://github.com/${{ github.repository }}" 
        -Ppom.scm.url="https://github.com/${{ github.repository }}" 
        publishToCentralPortal --no-daemon
  publish-javadoc:
    permissions:
      contents: write
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: repository
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: pages
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Javadoc with Gradle
      run: cd ./repository/ && ./gradlew javadoc
    - name: Move to GH Pages Branch
      run: |-
        mkdir --parents ./pages/javadoc/v${{ needs.version.outputs.version }}/
        mv ./repository/build/docs/javadoc/* ./pages/javadoc/v${{ needs.version.outputs.version }}/
        rm ./pages/javadoc/index.html
    - name: Generate Directory Listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        folder: ./pages/javadoc
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: ./pages
